Areas/IFAMS/Controllers/ECFDocDLController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using IEM.Areas.IFAMS.Models;
using IEM.Common;
using System.Threading.Tasks;
using System.Net;
using System.IO;
using Excel;
using System.Collections;
using System.Web.UI.WebControls;
using System.Web.UI;
using ClosedXML.Excel;
using ICSharpCode.SharpZipLib.Zip;
using System.IO.Compression;
using Ionic.Zip;
using System.Data.SqlClient;
using IEM.App_Start;

namespace IEM.Areas.ifams.Controllers
{

    [NoDirectAccess]
    public class ECFDocDLController : Controller
    {
        //
        // GET: /EOW/ECFDocDL/
        MASTERS.Controllers.ForMailController fm = new MASTERS.Controllers.ForMailController();
        DataModel dm = new DataModel();
        private CmnFunctions objcmnfunc = new CmnFunctions();
        ErrorLog objErrorLog = new ErrorLog();
        private FileServer objFs = new FileServer();
        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                Session["Assetqty"] = null;
                Session["AssetSerNo"] = null;
                Session["Assetdetid"] = null;
                //Session["accerr"] = null;
                Session["aqtyTempdataset"] = null;
                Session["aserTempdataset"] = null;
                Session["accfilename"] = null;
                Session["aqtyTempdatatable"] = null;
                Session["aserTempdatatable"] = null;
                Session["accgid"] = null;
                Session["aqtyerr"] = null;
                Session["asererr"] = null;
            }
            catch (Exception ex)
            {
                objErrorLog.WriteErrorLog(ex.Message.ToString(), ex.ToString());
            }
            finally
            {

            }
            return View();
        }
        public ActionResult ECFDocDLdownloadexcel()
        {

            using (DataTable dtnew = new DataTable())
            {
                dtnew.Columns.Add("SNo");
                dtnew.Columns.Add("ECF Number");
                //dtnew.Columns.Add("Remarks"); 
                using (XLWorkbook wb = new XLWorkbook())
                {
                    wb.Worksheets.Add(dtnew, "ECF_Template");

                    Response.Clear();
                    Response.Buffer = true;
                    Response.Charset = "";
                    Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                    Response.AddHeader("content-disposition", "attachment;filename=ECF_Template.xlsx");
                    using (MemoryStream MyMemoryStream = new MemoryStream())
                    {
                        wb.SaveAs(MyMemoryStream);
                        MyMemoryStream.WriteTo(Response.OutputStream);
                        Response.Flush();
                        Response.End();
                    }
                }
            }


            return View();
        }

        public JsonResult ECFDLUPdate(ECFDLDOCModel obj)
        {
            string mag = "";
            string strcols = "";
            string[] strColArr;
            try
            {
                DataSet resultacc = new DataSet();
                resultacc = (DataSet)Session["aqtyTempdataset"];
                var dataTable = new DataTable();
                dataTable = resultacc.Tables[obj.SheetName.ToString().Trim()];
                foreach (DataColumn dtColumn in dataTable.Columns)
                {
                    strcols = strcols + dtColumn.ColumnName.Trim() + ":";
                }
                strcols = strcols.Substring(0, strcols.Length - 1);
                strColArr = strcols.Split(':');
                if (strColArr[0].ToString() == "SNo"
                    && strColArr[1].ToString() == "ECF Number"
                                        && strColArr.Count().ToString() == "2")
                {
                    mag = "Success";
                }
                else
                {
                    mag = "Faild";
                }
                if (mag == "Success")
                {
                    if (dataTable.Rows.Count > 0)
                    {
                        int count = dataTable.Rows.Count;
                        for (int i = 0; i < count; i++)
                        {
                            if (dataTable.Rows[i]["SNo"].ToString() == ""
                                && dataTable.Rows[i]["ECF Number"].ToString() == ""
                                )
                            {
                                dataTable.Rows[i].Delete();
                                dataTable.AcceptChanges();
                                count--;
                                i--;
                            }
                        }
                        Session["aqtyTempdatatable"] = dataTable;
                    }
                }
            }
            catch (Exception ex)
            {
                objErrorLog.WriteErrorLog(ex.Message.ToString(), ex.ToString());
            }
            return Json(mag, JsonRequestBehavior.AllowGet);
        }
        public PartialViewResult ecfdlUploadstatus(string ddlSheetname)
        {
            try
            {
                if (Session["aqtyTempdatatable"] != null)
                {
                    DataTable errdataval = new DataTable();
                    errdataval = (DataTable)Session["aqtyTempdatatable"];
                    ecfdldatasupload(errdataval);
                    errdataval = (DataTable)Session["aqtyErrdatatable"];
                    if (errdataval.Rows.Count == 0)
                    {
                        ViewBag.visble = "Yes";
                    }
                }
            }
            catch (Exception ex)
            {
                objErrorLog.WriteErrorLog(ex.Message.ToString(), ex.ToString());
            }
            return PartialView();
        }
        public void ecfdldatasupload(DataTable dataTable)
        {
            int sno = 0;
            int totalrecord = 0;
            int invalid = 0;
            int valid = 0;
            // string duplicateasset = "";
            DataTable maindatatable = new DataTable();
            Hashtable empchck = new Hashtable();
            maindatatable = dataTable;
            totalrecord = maindatatable.Rows.Count;
            DataTable Errdatatable = new DataTable();
            Errdatatable.Columns.Add("SNo");
            Errdatatable.Columns.Add("Line");
            Errdatatable.Columns.Add("Error Description");
            try
            {
                if (dataTable.Rows.Count > 0)
                {
                    string exceltext = "";
                    string assetdata = "";
                    string status = "";
                    string errs = "";
                    string spgrpId1 = "";
                    string spgrpId2 = "";
                    string spRowCommaSeptated = "";
                    int RowNo = 0;
                    for (int i = 0; i < dataTable.Rows.Count; i++)
                    {
                        errs = "";
                        RowNo = i + 1;
                        assetdata = dataTable.Rows[i][1].ToString();
                        if (spRowCommaSeptated.Contains(assetdata) == true)
                        {
                            errs = "Duplicate ECF number Found";
                        }
                        else
                        {
                            if (dataTable.Rows[i][1].ToString() == "")
                            {
                                errs = "ECF number must not be empty";
                            }
                            else
                            {
                                exceltext = dataTable.Rows[i][1].ToString();
                                status = dm.GetStatusexcel(assetdata, exceltext, "ECFCheck");
                                if (status == "not")
                                {
                                    if (errs == "")
                                    {
                                        errs = "Invalid ECF Number";
                                    }
                                    else
                                    {
                                        errs = errs + "," + "Invalid ECF Number";
                                    }

                                }
                            }
                        }
                        if (errs != "")
                        {
                            sno++;
                            Errdatatable.Rows.Add(sno, RowNo, errs);
                        }
                    }
                }
                else
                {
                    Errdatatable.Rows.Add(1, "Please Select Valid Sheet");
                }
                invalid = Errdatatable.Rows.Count;
                valid = totalrecord - invalid;
                ViewBag.vbvalid = "Total No of Valid Record(s) :" + valid;
                ViewBag.vbinvalid = "Total No of Invalid Record(s) :" + invalid;
                ViewBag.vbtotalrecord = "Total No of Record(s) in Excel File :" + totalrecord;
                Session["aqtyErrdatatable"] = Errdatatable;
                Session["aqtymaindatatable"] = maindatatable;
            }
            catch (Exception ex)
            {
                objErrorLog.WriteErrorLog(ex.Message.ToString(), ex.ToString());
            }
        }
        public void ecfdlUploadFilesnew()
        {
            try
            {
                string filename = "";
                foreach (string file in Request.Files)
                {
                    var fileContent = Request.Files[file];

                    if (fileContent != null && fileContent.ContentLength > 0)
                    {
                        HttpPostedFileBase hpf = Request.Files[file] as HttpPostedFileBase;

Areas/IFAMS/Views/ECFDocDL/Index (2).cshtml
@model IEM.Areas.IFAMS.Models.ECFDLDOCModel
<link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/jquery-ui-1.8.24.min.js")" type="text/javascript"></script>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<div class="pageHeadingLayout">
    <span class="pageHeading">Download ECF's Documents</span>
</div>
<div id="headerAttachment">
    <div class="well" style="background-color:white">
        <div>
            <table class="myTableStyleTabNew" align="center">
                <tr>
                    <td>
                        <span>Select file</span><br />
                        <form id="theuploadformtrfma">
                            <input class="textboxStyleSearch" id="fileUploadTrfMaker" name="fileUploadTrfMaker" type="file" onchange="checkfile(this)" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel">
                        </form>
                    </td>
                    <td>
                        <span>Select Sheet</span>
                        <br />
                        @Html.DropDownListFor(model => model.SheetName, Enumerable.Empty<SelectListItem>(), "--Select--", new { @class = "textboxStyleSearch", @id = "ddlSelectsheet2", @name = "ddlSelectsheet2" })
                    </td>
                    <td id="idQty" 
                        <span>&nbsp;</span><br />
                        <div style="font-weight:bold">
                            <a class="btn" data-modal="" href="../ECFDocDL/ECFDocDLdownloadexcel" id="DownloadTemplate">
                                Download Template
                            </a>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
        <table class="myTableStyleTabNew" align="center">
            <tr>
                <td>
                    <span>&nbsp;</span><br />
                    <button id="btnfrstsubmit" class="btn btn-primary" value="Upload" onclick="UpdateQtynSerNo()"><span style="color:white;" class="glyphicon glyphicon-upload"></span> Upload</button>&nbsp;

                    &nbsp;<button id="btncanpayclear" onclick="txtClear()" class="btn btn-primary" value="cancel"><span style="color:white;" class="glyphicon glyphicon-remove-circle"></span> Clear</button>&nbsp;
                    &nbsp;<button id="btncanpayclear" onclick="backtotmsummary()" class="btn btn-warning" value="cancel"><span style="color:white;" class="glyphicon glyphicon-circle-arrow-left"></span> Cancel</button>

                </td>
            </tr>
        </table>

    </div>
</div>
<div id="dividuploadstatus"></div>

<script>
    var objforAttachment = $("[id$='dividuploadstatus']");
    $(document).ready(function () {


    });


    function UpdateQtynSerNo() {
        if ($("#fileUploadTrfMaker").val() == null || $("#fileUploadTrfMaker").val() == "") {
            jAlert("Please Select a valid file", "Message");
        }
        var sheet = $("#ddlSelectsheet2 option:selected").text();
        if (sheet == null || sheet == "0" || sheet == "--Select--") {
            jAlert("Please select a sheet", "Message");
            $("#ddlSelectsheet2").focus();
            return false;
        }
        else {
            var objsheet =
                 {
                     "Sheetname": sheet
                 };


            $.ajax({
                url: "@Url.Action("ECFDLUPdate", "ECFDocDL")?" + +new Date().getTime(),
                type: 'POST',
                cache: false,
                data: objsheet,
                success: function (data) {
                    if (data == "Success") {
                        $("#fileUploadTrfMaker").val("");
                        $("#theuploadformtrfma").val('');
                        objforAttachment.dialog({
                            autoOpen: false,
                            modal: true,
                            show: 'fade-in',
                            close: 'fade-out',
                            width: 400,
                            height: 300,
                            resizable: false
                        });
                        objforAttachment.load("@Url.Action("ecfdlUploadstatus", "ECFDocDL")?ddlSelectsheet2=" + sheet + '&' + new Date().getTime());
                        objforAttachment.dialog({ title: 'Upload Summary' });
                        objforAttachment.dialog("open");
                    }
                    else {
                        jAlert(" \tInvalid template." + "\n\t\t" + "   Please refer template.", "Message");
                        $("#fileUploadTrfMaker").val("")
                        txtClear();
                        return false;
                    }
                },
                error: function () {
                    jAlert("Please refer template.", "Message");
                    txtClear();
                    return false;
                }
            });

        }
    }


    function getsheets() {

        var data = "fff";
        $.ajax({
            type: "POST",
            url: '../ECFDocDL/ecfdlUploadFiles',
            contentType: false,
            processData: false,
            data: data,
            success: function (result) {
                $("#ddlSelectsheet2").empty();
                $("#ddlSelectsheet2").append("<option value='0' >---Select---</option>");
                if (result == "undefined" || result == "") {
                    jAlert("Please Upload File with Data", "Message");
                    txtClear();
                    return false;
                }
                else {
                    var err = result[0].aqtySheetname;
                    if (result.length > 0) {
                        var stylesSelect = $('#ddlSelectsheet2');
                        stylesSelect.attr('disabled', false);
                        for (var i = 0; i < result.length; i++) {
                            $("#ddlSelectsheet2").append("<option value=" + result[i].aqtySheetid + " >" + result[i].aqtySheetname + "</option>");
                        }
                    }
                    if (result.length == 0) {
                        var stylesSelect = $('#ddlSelectsheet2');
                        stylesSelect.attr('disabled', true);
                    }

                }
            },
            error: function (xhr, status, p3, p4) {
                var err = "Error " + " " + status + " " + p3 + " " + p4;
                if (xhr.responseText && xhr.responseText[0] == "{")
                    err = JSON.parse(xhr.responseText).Message;
                jAlert(err, "Error");
                txtClear();
                return false;
            }
        });
    }

    function backtotmsummary() {
        window.location.reload();
    }

    function checkfile(sender) {
        var validExts = new Array(".xlsx", ".xls");
        var fileExt = sender.value;
        fileExt = fileExt.substring(fileExt.lastIndexOf('.'));
        if (validExts.indexOf(fileExt) < 0) {
            jAlert("Invalid file selected, valid files are of " +
                     validExts.toString() + " types."); txtClear();
        }
        else {
            var iframe = $('<iframe name="postiframe" id="postiframe" style="display: none"></iframe>');
            $("body").append(iframe);
            var form = $('#theuploadformtrfma');
            form.attr("action", "../ECFDocDL/ecfdlUploadFilesnew");
            form.attr("method", "post");
            form.attr("encoding", "multipart/form-data");
            form.attr("enctype", "multipart/form-data");
            form.attr("target", "postiframe");
            form.attr("file", $('#fileUploadTrfMaker').val());
            form.submit();
            getsheets();

        }
    }

    function txtClear() {
        var fileUpload = $("[id*=fileUploadTrfMaker]");
        var id = fileUpload.attr("id");
        var name = fileUpload.attr("name");
        //Create a new FileUpload element.
        var newFileUpload = $("<input type = 'file' id='fileUploadTrfMaker' name='fileUploadTrfMaker' class='textboxStyleSearch' onchange='checkfile(this)' accept='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel' />");
        fileUpload.after(newFileUpload);
        fileUpload.remove();
        $("#ddlSelectsheet2").empty();
        $("#ddlSelectsheet2").append("<option value='0' >---Select---</option>");
    }
</script>

Areas/IFAMS/Views/ECFDocDL/Index (3).cshtml
@model IEM.Areas.IFAMS.Models.ECFDLDOCModel
<link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/jquery-ui-1.8.24.min.js")" type="text/javascript"></script>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<div class="pageHeadingLayout">
    <span class="pageHeading">Download ECF's Documents</span>
</div>
<div id="headerAttachment">
    <div class="well" style="background-color:white">
        <div>
            <table class="myTableStyleTabNew" align="center">
                <tr>
                    <td>
                        <span>Select file</span><br />
                        <form id="theuploadformtrfma">
                            <input class="textboxStyleSearch" id="fileUploadTrfMaker" name="fileUploadTrfMaker" type="file" onchange="checkfile(this)" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel">
                        </form>
                    </td>
                    <td>
                        <span>Select Sheet</span>
                        <br />
                        @Html.DropDownListFor(model => model.SheetName, Enumerable.Empty<SelectListItem>(), "--Select--", new { @class = "textboxStyleSearch", @id = "ddlSelectsheet2", @name = "ddlSelectsheet2" })
                    </td>
                    <td id="idQty" 
                        <span>&nbsp;</span><br />
                        <div style="font-weight:bold">
                            <a class="btn" data-modal="" href="../ECFDocDL/ECFDocDLdownloadexcel" id="DownloadTemplate">
                                Download Template
                            </a>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
        <table class="myTableStyleTabNew" align="center">
            <tr>
                <td>
                    <span>&nbsp;</span><br />
                    <button id="btnfrstsubmit" class="btn btn-primary" value="Upload" onclick="UpdateQtynSerNo()"><span style="color:white;" class="glyphicon glyphicon-upload"></span> Upload</button>&nbsp;

                    &nbsp;<button id="btncanpayclear" onclick="txtClear()" class="btn btn-primary" value="cancel"><span style="color:white;" class="glyphicon glyphicon-remove-circle"></span> Clear</button>&nbsp;
                    &nbsp;<button id="btncanpayclear" onclick="backtotmsummary()" class="btn btn-warning" value="cancel"><span style="color:white;" class="glyphicon glyphicon-circle-arrow-left"></span> Cancel</button>

                </td>
            </tr>
        </table>

    </div>
</div>
<div id="dividuploadstatus"></div>

<script>
    var objforAttachment = $("[id$='dividuploadstatus']");
    $(document).ready(function () {


    });


    function UpdateQtynSerNo() {
        if ($("#fileUploadTrfMaker").val() == null || $("#fileUploadTrfMaker").val() == "") {
            jAlert("Please Select a valid file", "Message");
        }
        var sheet = $("#ddlSelectsheet2 option:selected").text();
        if (sheet == null || sheet == "0" || sheet == "--Select--") {
            jAlert("Please select a sheet", "Message");
            $("#ddlSelectsheet2").focus();
            return false;
        }
        else {
            var objsheet =
                 {
                     "Sheetname": sheet
                 };


            $.ajax({
                url: "@Url.Action("ECFDLUPdate", "ECFDocDL")?" + +new Date().getTime(),
                type: 'POST',
                cache: false,
                data: objsheet,
                success: function (data) {
                    if (data == "Success") {
                        $("#fileUploadTrfMaker").val("");
                        $("#theuploadformtrfma").val('');
                        objforAttachment.dialog({
                            autoOpen: false,
                            modal: true,
                            show: 'fade-in',
                            close: 'fade-out',
                            width: 400,
                            height: 300,
                            resizable: false
                        });
                        objforAttachment.load("@Url.Action("ecfdlUploadstatus", "ECFDocDL")?ddlSelectsheet2=" + sheet + '&' + new Date().getTime());
                        objforAttachment.dialog({ title: 'Upload Summary' });
                        objforAttachment.dialog("open");
                    }
                    else {
                        jAlert(" \tInvalid template." + "\n\t\t" + "   Please refer template.", "Message");
                        $("#fileUploadTrfMaker").val("")
                        txtClear();
                        return false;
                    }
                },
                error: function () {
                    jAlert("Please refer template.", "Message");
                    txtClear();
                    return false;
                }
            });

        }
    }


    function getsheets() {

        var data = "fff";
        $.ajax({
            type: "POST",
            url: '../ECFDocDL/ecfdlUploadFiles',
            contentType: false,
            processData: false,
            data: data,
            success: function (result) {
                $("#ddlSelectsheet2").empty();
                $("#ddlSelectsheet2").append("<option value='0' >---Select---</option>");
                if (result == "undefined" || result == "") {
                    jAlert("Please Upload File with Data", "Message");
                    txtClear();
                    return false;
                }
                else {
                    var err = result[0].aqtySheetname;
                    if (result.length > 0) {
                        var stylesSelect = $('#ddlSelectsheet2');
                        stylesSelect.attr('disabled', false);
                        for (var i = 0; i < result.length; i++) {
                            $("#ddlSelectsheet2").append("<option value=" + result[i].aqtySheetid + " >" + result[i].aqtySheetname + "</option>");
                        }
                    }
                    if (result.length == 0) {
                        var stylesSelect = $('#ddlSelectsheet2');
                        stylesSelect.attr('disabled', true);
                    }

                }
            },
            error: function (xhr, status, p3, p4) {
                var err = "Error " + " " + status + " " + p3 + " " + p4;
                if (xhr.responseText && xhr.responseText[0] == "{")
                    err = JSON.parse(xhr.responseText).Message;
                jAlert(err, "Error");
                txtClear();
                return false;
            }
        });
    }

    function backtotmsummary() {
        window.location.reload();
    }

    function checkfile(sender) {
        var validExts = new Array(".xlsx", ".xls");
        var fileExt = sender.value;
        fileExt = fileExt.substring(fileExt.lastIndexOf('.'));
        if (validExts.indexOf(fileExt) < 0) {
            jAlert("Invalid file selected, valid files are of " +
                     validExts.toString() + " types."); txtClear();
        }
        else {
            var iframe = $('<iframe name="postiframe" id="postiframe" style="display: none"></iframe>');
            $("body").append(iframe);
            var form = $('#theuploadformtrfma');
            form.attr("action", "../ECFDocDL/ecfdlUploadFilesnew");
            form.attr("method", "post");
            form.attr("encoding", "multipart/form-data");
            form.attr("enctype", "multipart/form-data");
            form.attr("target", "postiframe");
            form.attr("file", $('#fileUploadTrfMaker').val());
            form.submit();
            getsheets();

        }
    }

    function txtClear() {
        var fileUpload = $("[id*=fileUploadTrfMaker]");
        var id = fileUpload.attr("id");
        var name = fileUpload.attr("name");
        //Create a new FileUpload element.
        var newFileUpload = $("<input type = 'file' id='fileUploadTrfMaker' name='fileUploadTrfMaker' class='textboxStyleSearch' onchange='checkfile(this)' accept='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel' />");
        fileUpload.after(newFileUpload);
        fileUpload.remove();
        $("#ddlSelectsheet2").empty();
        $("#ddlSelectsheet2").append("<option value='0' >---Select---</option>");
    }
</script>

Areas/IFAMS/Views/ECFDocDL/ecfdlUploadstatus (2).cshtml
<br />

<table class="myTableStyleTabNew" align="center">
    <tr>
        <td>
            <div style="font-weight:bold;">@ViewBag.vbtotalrecord</div>
        </td>
    </tr>
    <tr>
        <td>
            <div style="font-weight:bold;">@ViewBag.vbvalid</div>
        </td>
    </tr>
    <tr>
        <td>
            <div style="font-weight:bold;">@ViewBag.vbinvalid</div>
        </td>
    </tr>
</table>

<table align="center" class="myTableStyleTabNew">
    <tr>
        <td>
            @if (@ViewBag.visble == "Yes")
            {
                <div style="font-weight:bold ; width:150%">
                    <a class="btn btn-success" style="color:white;" data-modal="" href="../ECFDocDL/ECFDLlocaldetails" id="ViewErrorLog" onclick="GotoIndexclose()">
                        <span style="color:white;" class="glyphicon glyphicon-download"></span> Download Docs
                    </a>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <button class="btn btn-warning" type="button" id="btncancelexcel" value="Cancel" onclick="GotoIndexClose()"><span style="color:white;" class="glyphicon glyphicon-remove-sign"></span> Cancel</button>


                </div>
            }
        </td>
        <td>
            @if (@ViewBag.visble != "Yes")
            {
                <div style="font-weight:bold">
                    <a class="btn btn-warning" style="color:white;" data-modal="" href="../ECFDocDL/ECFDocDLErrdownloadsexcel" id="ViewErrorLog" onclick="GotoIndexclose()">
                        <span style="color:white;" class="glyphicon glyphicon-download"></span> View Error Log
                    </a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <button class="btn btn-primary" type="button" id="btncancelexcel1" value="Close" onclick="GotoIndexclose()"><span style="color:white;" class="glyphicon glyphicon-remove"></span> Close</button>

                </div>
            }
        </td>
    </tr>
</table>



<script>

    $(document).ready(function () {
        $("#btnok").click(function () {
            window.parent.jQuery('#forAttachment').dialog('close');
            objforAttachment.dialog("close");
            var value = "fgdf";
            var objcbf =
        {
            "empid": value
        };
            $.ajax({
                url: "../ECFDocDL/ECFDLlocaldetails/",
                type: 'POST',
                cache: false,
                data: objcbf//,
                @*success: function (data) {
                    $("#processworkingdata").empty();
                    var url = "@(Html.Raw(Url.Action("ECFDLlocaldetails", "ECFDocDL")))";
                    $("#processworkingdata").load(url);
                    //alert(data);
                    if (data == "Success") {
                        jAlert("Downloaded Successfully!!", "Information", function (r) {
                            if (r == true) {
                                location = '../ECFDocDL/ECFDocDLSerialno';
                            }
                        });

                        objforAttachment.dialog("close");
                        window.parent.jQuery('#forAttachment').dialog('close');
                    }
                    else {
                        jAlert("Download update failed!!", "Message");
                    }
                },
                error: function () {
                    jAlert("Download failed with error!!", "Information");
                    return false;
                }*@
            });
        });
    });
    function GotoIndexclose() {
        objforAttachment.dialog("close");
        window.parent.jQuery('#forAttachment').dialog('close');
    }
    function GotoIndexClose() {
        objforAttachment.dialog("close");
        window.parent.jQuery('#forAttachment').dialog('close');
        jAlert("Download was cancelled!!", "Information");
    }



</script>