Areas/FLEXISPEND/Controllers/FAReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IEM.Helper;
using Newtonsoft.Json;
using IEM.Areas.FLEXISPEND.Models;
using System.Data;
using ClosedXML.Excel;
using System.IO;
using IEM.App_Start;
namespace IEM.Areas.FLEXISPEND.Controllers
{

    [NoDirectAccess]
    public class FAReportController : Controller
    {

        #region Declaration
        proLib pl = new proLib();
        dbLib db = new dbLib();
        DataTable dt;
        #endregion

        //
        // GET: /FLEXISPEND/FAReport/
        public ActionResult AdvanceReport()
        {
            return View();
        }

        [HttpPost]
        public JsonResult FetchAdvanceReport(string Date, string Dateto, string ECFNo, string EmpId, string SuppId, string Raiserid, string glno, string Branch)
        {
            try
            {
               
                string Data1 = "", Data2 = "";
                DataSet ds = db.FetchAdvanceReport(Date, Dateto, ECFNo, EmpId, SuppId, Raiserid, glno, Branch, pl.LoginUserId);
                if (ds != null && ds.Tables.Count > 1)
                {
                    dt = ds.Tables[0];
                    if (dt.Rows.Count > 0) { Data1 = JsonConvert.SerializeObject(dt); }

                    dt = ds.Tables[1];
                    if (dt.Rows.Count > 0) { Data2 = JsonConvert.SerializeObject(dt); }
                }
                var jsonResult = Json(new { Data1, Data2 }, JsonRequestBehavior.AllowGet);
               // return Json(Data2 , JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;
            }
            catch
            {
                return null;
            }
        }

        [HttpPost]
        public JsonResult DownloadAdvanceReport(string Date, string Dateto, string ECFNo, string EmpId, string SuppId, string Raiserid, string glno, string branch)
        {
            try
            {
                Session["ARDownlinkFile"] = null;
                string Data1 = "";
                DataSet ds = db.FetchAdvanceReport(Date, Dateto, ECFNo, EmpId, SuppId, Raiserid, glno, branch, pl.LoginUserId);
                if (ds != null && ds.Tables.Count > 1)
                {
                    dt = ds.Tables[1];
                    if (dt.Rows.Count > 0)
                    {
                        try
                        {
                            
                            DataTable _tmpdata = ds.Tables[1];
                            _tmpdata.Columns.RemoveAt(1);
                            _tmpdata.TableName = "AdvanceRpt";
                            Session["ARDownlinkFile"] = _tmpdata;
                            if (_tmpdata != null && _tmpdata.Rows.Count > 0)
                            {
                                Data1 = "process";
                            }
                        }
                        catch
                        {
                            Session["ARDownlinkFile"] = null;
                        }
                    }
                }
                return Json(Data1, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return null;
            }
        }

        //downloading Advance Excel File
        public JsonResult DownloadExcelAdavanceRpt()
        {
            DataTable _downloadingData = Session["ARDownlinkFile"] as DataTable;
            if (_downloadingData != null)
            {
                using (XLWorkbook wb = new XLWorkbook())
                {
                    wb.Worksheets.Add(_downloadingData);
                    wb.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                    wb.Style.Font.Bold = true;

                    Response.Clear();
                    Response.Buffer = true;
                    Response.Charset = "";
                    Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                    Response.AddHeader("content-disposition", "attachment;filename= FA Advance Report.xlsx");

                    using (MemoryStream MyMemoryStream = new MemoryStream())
                    {
                        wb.SaveAs(MyMemoryStream);
                        MyMemoryStream.WriteTo(Response.OutputStream);
                        Response.Flush();
                        Response.End();
                    }
                }
            }

            return Json("", JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /FLEXISPEND/FAReport/
        public ActionResult Retention()
        {
            return View();
        }

        [HttpPost]
        public JsonResult FetchRetentionReport(string Date, string ECFNo, string EmpId, string SuppId)
        {
            try
            {
                string Data1 = "", Data2 = "";
                DataSet ds = db.FetchRetentionReport(pl.ConvertDate(Date == null ? "" : Date), ECFNo, EmpId, SuppId, pl.LoginUserId);
                if (ds != null && ds.Tables.Count > 1)
                {
                    dt = ds.Tables[0];
                    if (dt.Rows.Count > 0) { Data1 = JsonConvert.SerializeObject(dt); }

                    dt = ds.Tables[1];
                    if (dt.Rows.Count > 0) { Data2 = JsonConvert.SerializeObject(dt); }
                }
                return Json(new { Data1, Data2 }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return null;
            }
        }

        [HttpPost]
        public JsonResult DownloadRetentionReport(string Date, string ECFNo, string EmpId, string SuppId)
        {
            try
            {
                Session["RRDownlinkFile"] = null;
                string Data1 = "";
                DataSet ds = db.FetchRetentionReport(pl.ConvertDate(Date == null ? "" : Date), ECFNo, EmpId, SuppId, pl.LoginUserId);
                if (ds != null && ds.Tables.Count > 1)
                {
                    dt = ds.Tables[1];
                    if (dt.Rows.Count > 0)
                    {
                        try
                        {
                            DataTable _tmpdata = ds.Tables[1];
                            _tmpdata.Columns.RemoveAt(1);
                            _tmpdata.TableName = "RetentionRpt";
                            Session["RRDownlinkFile"] = _tmpdata;
                            if (_tmpdata != null && _tmpdata.Rows.Count > 0) {
                                Data1 = "process";
                            }
                        }
                        catch
                        {
                            Session["RRDownlinkFile"] = null;
                        }
                    }
                }
                return Json(Data1, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return null;
            }
        }

        //downloading Retention Excel File
        public JsonResult DownloadExcelRetentionRpt()
        {
            DataTable _downloadingData = Session["RRDownlinkFile"] as DataTable;
            if (_downloadingData != null)
            {
                using (XLWorkbook wb = new XLWorkbook())
                {
                    wb.Worksheets.Add(_downloadingData);
                    wb.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                    wb.Style.Font.Bold = true;

                    Response.Clear();
                    Response.Buffer = true;
                    Response.Charset = "";
                    Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                    Response.AddHeader("content-disposition", "attachment;filename= FA Retention Report.xlsx");

                    using (MemoryStream MyMemoryStream = new MemoryStream())
                    {
                        wb.SaveAs(MyMemoryStream);
                        MyMemoryStream.WriteTo(Response.OutputStream);
                        Response.Flush();
                        Response.End();
                    }
                }
            }

            return Json("", JsonRequestBehavior.AllowGet);
        }
        //
        // GET: /FLEXISPEND/FAReport/
        public ActionResult Sale()
        {
            return View();
        }

        [HttpPost]
        public JsonResult FetchSalesReport(string DateFrom, string DateTo)
        {
            try
            {
                string Data1 = "", Data2 = "";
                DataSet ds = db.FetchSalesReport(pl.ConvertDate(DateFrom == null ? "" : DateFrom), pl.ConvertDate(DateTo == null ? "" : DateTo), pl.LoginUserId);
                if (ds != null && ds.Tables.Count > 1)
                {
                    dt = ds.Tables[0];
                    if (dt.Rows.Count > 0) { Data1 = JsonConvert.SerializeObject(dt); }

                    dt = ds.Tables[1];
                    if (dt.Rows.Count > 0) { Data2 = JsonConvert.SerializeObject(dt); }
                }
                return Json(new { Data1, Data2 }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return null;
            }
        }

        [HttpPost]
        public JsonResult DownloadSaleReport(string DateFrom, string DateTo)
        {
            try
            {
                Session["SRDownlinkFile"] = null;
                string Data1 = "";
                DataSet ds = db.FetchSalesReport(pl.ConvertDate(DateFrom == null ? "" : DateFrom), pl.ConvertDate(DateTo == null ? "" : DateTo), pl.LoginUserId);
                if (ds != null && ds.Tables.Count > 1)
                {
                    dt = ds.Tables[1];
                    if (dt.Rows.Count > 0)
                    {
                        try
                        {
                            DataTable _tmpdata = ds.Tables[1];

Areas/FLEXISPEND/Views/FAReport/AdvanceReport.cshtml
@{
    ViewBag.Title = "AdvanceReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/Rmax_Site.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/jquery-ui-1.8.24.min.js")" type="text/javascript"></script>
<style>
    table, th, td {
        white-space: nowrap;
    }
</style>

<div class="pageHeadingLayout">
    <span class="pageHeading">FA Advance Report</span>
</div>
<div class="well">
    <table class="myTableStyleTabNew" style="width:100%;">
        <tr>
            <td style="width:25%; padding:0px 10px 0px 3px;">
                <span>Date From</span>
                <br />
                <input type="text"
                       id="txtDate"
                       @*disabled ="disabled"*@
                       @*value="@DateTime.Now.ToString("dd'/'MM'/'yyyy")"*@
                       onkeypress="return isEvent(event)"
                       class="fstextbox" />
            </td>
            <td style="width:25%; padding:0px 10px 0px 3px;">
                <span>Date To</span>
                <br />
                <input type="text"
                       id="txtDateto"
                       @*disabled ="disabled"*@
                       @*value="@DateTime.Now.ToString("dd'/'MM'/'yyyy")"*@
                       onkeypress="return isEvent(event)"
                       class="fstextbox" />
            </td>
            <td style="width:25%; padding:0px 10px;">
                <span>Vendor </span>
                <br />
                <input type="text"
                       id="txtVendor"
                       name="txtVendor"
                       class="fstextbox" />
                <input type="hidden" id="hfVendor" value="0" />
            </td>
            <td style="width:25%; padding:0px 10px;">
                <span> ECF No</span>
                <br />
                <input type="text"
                       id="txtECFNo"
                       name="txtECFNo"
                       class="fstextbox" />
            </td>
            </tr>
            <tr>
            <td style="width:25%; padding:0px 10px;">
                <span> GL No</span>
                <br />
                <input type="hidden" id="hdfGL" value="0" />
                <input type="text"
                       id="txtGl"
                       name="txtGL"
                       class="fstextbox" />
            </td>

            <td style="width:25%; padding:0px 10px;">
                <span> Raiser</span>
                <br />
                <input type="hidden" id="hdfRaiser" value="0" />
                <input type="text"
                       id="txtRaiser"
                       name="txtRaiser"
                       class="fstextbox" />
            </td>

                <td style="width:25%; padding:0px 10px;">
                    <span> Branch</span>
                    <br />
                    <input type="hidden" id="hdfbranch" value="0" />
                    <input type="text"
                           id="txtbranch"
                           name="txtbranch"
                           class="fstextbox" />
                </td>

            <td style="width:25%; padding:0px; vertical-align:bottom;">
                <button class="btn btn-primary" id="btnsearch" data-bind="click: $root.search" style="color:white; margin-bottom:3px;">
                    <span style="color:white; font-size:12px;" class="glyphicon glyphicon-search"></span>
                    Search
                </button>
                <button class="btn btn-primary" data-bind="click: $root.clearFilter" style="color:white; margin-bottom:3px;">
                    <span style="color:white; font-size:12px;" class="glyphicon glyphicon-refresh"></span>
                    Clear
                </button>
                <button class="btn btn-success" id="btnExporExcel" data-bind="click: $root.Download" style="color:white; margin-bottom:3px;">
                    <span style="color:white; font-size:12px;" class="glyphicon glyphicon-export"></span>
                    Export to Excel
                </button>
            </td>
        </tr>
    </table>
    <div style="width:100%; overflow:auto; height:100%; margin-top: 15px;">
        <table class="tableSmall table-bordered table-hover table-responsive" id="gvReport" data-bind="visible: ResultArray().length > 0">
            <thead>
                <tr>
                    <th style="width:2%; min-width:40px; max-width:100%;">
                        S No
                    </th>
                    <th style="width:4%; min-width:100px; max-width:100%">
                        ARFNo
                    </th>
                    <th style="width:5%; min-width:100px; max-width:100%;">
                        Raiser Code
                    </th>
                    <th style="width:7%; min-width:150px; max-width:100%;">
                        Raiser Name
                    </th>
                    <th style="width:5%; min-width:120px; max-width:100%;">
                        Advance Amount
                    <th style="width:5%; min-width:120px; max-width:100%;">
                        Liquidation Amount
                    </th>
                    <th style="width:5%; min-width:120px; max-width:100%;">
                        Outstanding Amount
                    </th>
                    <th style="width:5%; min-width:100px; max-width:100%;">
                        Location Code
                    </th>
                    <th style="width:5%; min-width:100px; max-width:100%;">
                        GL Code
                    </th>
                    <th style="width:7%; min-width:150px; max-width:100%;">
                        Vendor Name
                    </th>
                    <th style="width:5%; min-width:100px; max-width:100%;">
                        Gross Amount
                    </th>
                    <th style="width:5%; min-width:100px; max-width:100%;">
                        TDS Amount
                    </th>
                    <th style="width:5%; min-width:100px; max-width:100%;">
                        WCT Amount
                    </th>
                    <th style="width:5%; min-width:100px; max-width:100%;">
                        Net Amount
                    </th>
                    <th style="width:7%; min-width:150px; max-width:100%;" class="nosort">
                        Purpose
                    </th>
                    <th style="width:5%; min-width:100px; max-width:100%;" class="colDate">
                        Process Date
                    </th>
                    <th style="width:4%; min-width:100px; max-width:100%;">
                        Ageing
                    </th>
                    <th style="width:4%; min-width:100px; max-width:100%;">
                        Bucket
                    </th>
                    <th style="width:5%; min-width:100px; max-width:100%;" class="colDate">
                        Target Date
                    </th>
                    <th style="width:5%; min-width:120px; max-width:100%;">
                        Department
                    </th>
                </tr>
            </thead>
            <tbody data-bind="foreach:{ data: ResultArray, afterRender: DatatableCall }, visible: ResultArray().length > 0">
                <tr>
                    <td align="center">
                        <span data-bind="text: SlNo"></span>
                    </td>
                    <td>
                        <span data-bind="text: DocNo"></span>
                    </td>
                    <td>
                        <span data-bind="text: RaiserCode"></span>
                    </td>
                    <td>
                        <span data-bind="text: RaiserName"></span>
                    </td>
                    <td align="right">
                        <span data-bind="text: $root.formatNumber(ECFARFAmount)"></span>
                    </td>
                    <td align="right">
                        <span data-bind="text: $root.formatNumber(LiquidationAmount)"></span>
                    </td>
                    <td align="right">
                        <span data-bind="text: $root.formatNumber(OutStandingAmount)"></span>
                    </td>
                    <td>
                        <span data-bind="text: LocationCode"></span>
                    </td>
                    <td>
                        <span data-bind="text: GLCode"></span>
                    </td>
                    <td>
                        <span data-bind="text: EmployeeSupplierName"></span>
                    </td>
                    <td align="right">
                        <span data-bind="text: $root.formatNumber(GrossAmount)"></span>
                    </td>
                    <td align="right">
                        <span data-bind="text: $root.formatNumber(TDSAmount)"></span>
                    </td>
                    <td align="right">
                        <span data-bind="text: $root.formatNumber(WCTAmount)"></span>
                    </td>
                    <td align="right">
                        <span data-bind="text: $root.formatNumber(NetAmount)"></span>
                    </td>
                    <td>
                        <span data-bind="text: Purpose"></span>
                    </td>
                    <td align="center">
                        <span data-bind="text: ProcessDate"></span>
                    </td>
                    <td>
                        <span data-bind="text: Ageing"></span>
                    </td>
                    <td>
                        <span data-bind="text: Bucket"></span>
                    </td>
                    <td align="center">
                        <span data-bind="text: LiquidationDate"></span>
                    </td>
                    <td>
                        <span data-bind="text: Department"></span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<script>
    var UrlDet = "@Url.Action("AdvanceReport", "FAReport")"
    var UrlHelper = "@Url.Action("GetAutoCompleteCourier", "Helper")"
</script>
<script src="@Url.Content("~/Areas/FLEXISPEND/FS_UserScript/jsAdvanceReport.js")" type="text/javascript"></script>

Areas/FLEXISPEND/Views/FAReport/CBFTracker.cshtml
@{
    ViewBag.Title = "CBFTracker";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/Rmax_Site.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/jquery-ui-1.8.24.min.js")" type="text/javascript"></script>
<style>
    table, th, td {
        white-space: nowrap;
    }
</style>
<div class="pageHeadingLayout">
    <span class="pageHeading">CBF Tracker Report</span>
</div>
<div class="well">
    <table class="myTableStyleTabNew" style="width:100%;">
        <tr>
            <td style="width:25%; ">
                <span>Status </span>
                <br />
                <select id="ddlStatus" class="fstextbox">
                    <option selected="selected" value="ALL"> All</option>
                    <option value="Pending"> Pending</option>
                    <option value="Approval"> Approval</option>
                    <option value="Reject"> Reject</option>
                </select>
            </td>
            <td style="width:75%;  vertical-align:bottom;">
                <button class="btn btn-primary" id="btnsearch" style="color:white; margin-bottom:3px;" data-bind="click: $root.Search">
                    <span style="color:white; font-size:12px;" class="glyphicon glyphicon-search"></span>
                    Search
                </button>
                <button class="btn btn-primary" data-bind="click: $root.clearFilter" style="color:white; margin-bottom:3px;">
                    <span style="color:white; font-size:12px;" class="glyphicon glyphicon-refresh"></span>
                    Clear
                </button>
                <button class="btn btn-success" id="btnExporExcel" data-bind="click: $root.Download" style="color:white;">
                    <span style="color:white; font-size:12px;" class="glyphicon glyphicon-export"></span>
                    Export to Excel
                </button>
            </td>
        </tr>
    </table>
    <div style="width:100%; overflow:auto; height:100%; margin-top: 15px;">
        <table id="gvReport" class="tableSmall table-bordered table-hover" data-bind="visible: CBFTrackingArray().length > 0">
            <thead data-bind="visible: columnNames().length > 0">
                <tr data-bind="foreach: columnNames">
                    <th style="min-width:80px; max-width:100%;">
                        <span data-bind="text: $data"></span>
                    </th>
                </tr>
            </thead>
            <tbody data-bind="foreach:{ data: CBFTrackingArray, afterRender: DatatableCall }">
                <tr data-bind="foreach: $parent.columnNames">
                    <td>
                        <span data-bind="text: $parent[$data]"></span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<script>
    var UrlDet = "@Url.Action("FetchCBFTrackerReport", "FAReport")"
    var UrlHelper = "@Url.Action("GetAutoCompleteCourier", "Helper")"
</script>
<script src="@Url.Content("~/Areas/FLEXISPEND/FS_UserScript/jsCBFTracker.js")" type="text/javascript"></script>

Areas/FLEXISPEND/Views/FAReport/SaleInvoiceTracker.cshtml
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/Rmax_Site.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/jquery-ui-1.8.24.min.js")" type="text/javascript"></script>
<style>
    table, th, td {
        white-space: nowrap;
    }
</style>

<div class="pageHeadingLayout">
    <span class="pageHeading">Sale Invoice Tracker</span>
</div>
<div class="well">
    <table class="myTableStyleTabNew" style="width:100%;">
        <tr>
            <td style="width:25%; padding:0px 10px 0px 3px;">
                <span>Date From</span>
                <br />
                <input type="text"
                       id="txtDateFrom"
                       onkeypress="return isEvent(event)"
                       class="fstextbox" />
            </td>
            <td style="width:25%; padding:0px 10px;">
                <span>Date To</span>
                <br />
                <input type="text"
                       id="txtDateTo"
                       onkeypress="return isEvent(event)"
                       class="fstextbox" />
            </td>
            <td style="width:50%; padding:0px; vertical-align:bottom;">
                <button class="btn btn-primary" data-bind="click: $root.search" style="color:white;">
                    <span style="color:white; font-size:12px;" class="glyphicon glyphicon-search"></span>
                    Search
                </button>
                <button class="btn btn-primary" data-bind="click: $root.clearFilter" style="color:white;">
                    <span style="color:white; font-size:12px;" class="glyphicon glyphicon-refresh"></span>
                    Clear
                </button>
                <button class="btn btn-success" id="btnExporExcel" data-bind="click: $root.Download" style="color:white;">
                    <span style="color:white; font-size:12px;" class="glyphicon glyphicon-export"></span>
                    Export to Excel
                </button>
            </td>
        </tr>
    </table>
    <div style="width:100%; overflow:auto; height:100%; margin-top: 15px;">
        <table class="tableSmall table-bordered table-hover table-responsive" id="gvReport" data-bind="visible: ResultArray().length > 0">
            <thead>
                <tr>
                    <th style="width:4%; min-width:40px; max-width:100%;">
                        SlNo
                    </th>
                    <th style="width:8%; min-width:120px; max-width:100%;">
                        Invoice No
                    </th>
                    <th style="width:8%; min-width:100px;  max-width:100%;" class="colDate">
                        Invoice Date
                    </th>
                    <th style="width:8%; min-width:120px; max-width:100%;">
                        Branch Code
                    </th>
                    <th style="width:8%; min-width:180px; max-width:100%;">
                        State
                    </th>
                    <th style="width:7%; min-width:130px; max-width:100%;">
                        Vat Rate
                    </th>
                    <th style="width:10%; min-width:180px; max-width:100%;">
                        Department
                    </th>
                    <th style="width:7%; min-width:130px; max-width:100%;">
                        Total Sales Value
                    </th>
                    <th style="width:7%; min-width:130px; max-width:100%;">
                        Sales Net Value
                    </th>
                    <th style="width:7%; min-width:130px;  max-width:100%;">
                        VAT Amount
                    </th>
                    <th style="width:10%; min-width:180px;  max-width:100%;">
                        Buyer Name
                    </th>
                    <th style="width:16%; min-width:250px;  max-width:100%;">
                        Buyer Address
                    </th>
                </tr>
            </thead>
            <tbody data-bind="foreach:{ data: ResultArray, afterRender: DatatableCall }, visible: ResultArray().length > 0">
                <tr>
                    <td align="center">
                        <span data-bind="text: SlNo"></span>
                    </td>
                    <td>
                        <span data-bind="text: InvoiceNo"></span>
                    </td>
                    <td align="center">
                        <span data-bind="text: InvoiceDate"></span>
                    </td>
                    <td>
                        <span data-bind="text: BranchCode"></span>
                    </td>
                    <td>
                        <span data-bind="text: State"></span>
                    </td>
                    <td align="right">
                        <span data-bind="text: $root.formatNumber(VatRate)"></span>
                    </td>
                    <td>
                        <span data-bind="text: Dept"></span>
                    </td>
                    <td align="right">
                        <span data-bind="text: $root.formatNumber(TotalSalesValue)"></span>
                    </td>
                    <td align="right">
                        <span data-bind="text: $root.formatNumber(SalesNetValue)"></span>
                    </td>
                    <td align="right">
                        <span data-bind="text: $root.formatNumber(VatAmount)"></span>
                    </td>
                    <td>
                        <span data-bind="text: BuyerName"></span>
                    </td>
                    <td>
                        <span data-bind="text: BuyerAddress"></span>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<script>
    var UrlDet = "@Url.Action("FetchSaleInvoiceTrackerReport", "FAReport")"
</script>
<script src="@Url.Content("~/Areas/FLEXISPEND/FS_UserScript/jsIFAMSSaleInvoiceTrackerReport.js")" type="text/javascript"></script>